- README.md
> Add Gradle Usage

- src/main/java/javaslang/jackson/datatype/deserialize/BaseDeserializer.java
- src/test/java/javaslang/jackson/datatype/BeanTest.java
> Add Test for Serialize/Deserialize ComplexBean

- src/test/java/javaslang/jackson/datatype/ComplexBeanTest.java
- src/test/java/javaslang/jackson/datatype/bean/ComplexClass.java
i add test for ComplexClass Structure. 
Found a problem with Tuple2 deserializer.
cc @ruslansennov
> Add Test for ComplexBean

- README.md
- pom.xml
> Bump Version 2.0.1

- src/main/java/javaslang/jackson/datatype/serialize/OptionSerializer.java
- src/main/java/javaslang/jackson/datatype/serialize/ValueSerializer.java
- src/test/java/javaslang/jackson/datatype/bean/BeanAnnotationTest.java
Add null default serializer in order to support ignore annotations
> Add null default serializer in order to support ignore annotations

- src/main/java/javaslang/jackson/datatype/deserialize/MaplikeDeserializer.java
- src/main/java/javaslang/jackson/datatype/deserialize/ValueDeserializer.java
- src/test/java/javaslang/jackson/datatype/PolymorphicTypesTest.java
> 66: add ability to use polymorphic types

- pom.xml
- src/main/java/javaslang/jackson/datatype/deserialize/EitherDeserializer.java
- src/test/java/javaslang/jackson/datatype/EitherTest.java
See related issue: https://github.com/javaslang/javaslang-jackson/compare/master...Diagoras:98?expand=1
> #98: Ensure consistency with JacksonScalaModule's Either serialization/deserialization

- .travis.yml
- pom.xml
- src/main/java/javaslang/jackson/datatype/JavaslangTypeModifier.java
- src/main/java/javaslang/jackson/datatype/deserialize/ArrayDeserializer.java
- src/main/java/javaslang/jackson/datatype/deserialize/EitherDeserializer.java
- src/main/java/javaslang/jackson/datatype/deserialize/JavaslangDeserializers.java
- src/main/java/javaslang/jackson/datatype/deserialize/MultimapDeserializer.java
- src/main/java/javaslang/jackson/datatype/deserialize/OptionDeserializer.java
- src/main/java/javaslang/jackson/datatype/deserialize/TupleDeserializer.java
- src/main/java/javaslang/jackson/datatype/deserialize/ValueDeserializer.java
- src/main/java/javaslang/jackson/datatype/serialize/ArraySerializer.java
- src/main/java/javaslang/jackson/datatype/serialize/CharSeqSerializer.java
- src/main/java/javaslang/jackson/datatype/serialize/JavaslangSerializers.java
- src/main/java/javaslang/jackson/datatype/serialize/LazySerializer.java
- src/main/java/javaslang/jackson/datatype/serialize/MapSerializer.java
- src/main/java/javaslang/jackson/datatype/serialize/MultimapSerializer.java
- src/main/java/javaslang/jackson/datatype/serialize/OptionSerializer.java
- src/main/java/javaslang/jackson/datatype/serialize/SerializableSerializer.java
- src/main/java/javaslang/jackson/datatype/serialize/TupleSerializer.java
- src/main/java/javaslang/jackson/datatype/serialize/ValueSerializer.java
- src/test/java/javaslang/jackson/datatype/bean/AbstractContent.java
- src/test/java/javaslang/jackson/datatype/bean/AbstractContentTest.java
> jackson v.2.8.4 support

- src/main/java/javaslang/jackson/datatype/deserialize/MapDeserializer.java
- src/test/java/javaslang/jackson/datatype/map/TreeMapTest.java
towards [this](https://github.com/javaslang/javaslang-jackson/issues/75#issuecomment-276615088) comment
> fix SortedMap deserialization

- src/main/java/io/vavr/jackson/datatype/serialize/VavrSerializers.java
- src/test/java/io/vavr/jackson/datatype/OptionTest.java
VavrModule is serializing bad class - when trying to serialize
Option including an object implementing abstract class / interface,
it only serialize abstract class / interface getters / fields.
> Fixed bug: #114

- .travis.yml
- pom.xml
- src/main/java/io/vavr/jackson/datatype/serialize/HListSerializer.java
- src/main/java/io/vavr/jackson/datatype/serialize/LazySerializer.java
- src/main/java/io/vavr/jackson/datatype/serialize/OptionSerializer.java
- src/main/java/io/vavr/jackson/datatype/serialize/VavrSerializers.java
- src/test/java/io/vavr/jackson/datatype/LazyTest.java
- src/test/java/io/vavr/jackson/datatype/OptionPlainTest.java
- src/test/java/io/vavr/jackson/datatype/OptionTest.java
> fix pojo serialization

- src/main/java/io/vavr/jackson/datatype/deserialize/MaplikeDeserializer.java
- src/main/java/io/vavr/jackson/datatype/deserialize/PriorityQueueDeserializer.java
- src/main/java/io/vavr/jackson/datatype/deserialize/SetDeserializer.java
- src/test/java/io/vavr/jackson/datatype/BaseTest.java
- src/test/java/io/vavr/jackson/datatype/PriorityQueueTest.java
- src/test/java/io/vavr/jackson/datatype/map/MapTest.java
- src/test/java/io/vavr/jackson/datatype/multimap/MultimapTest.java
- src/test/java/io/vavr/jackson/datatype/seq/SeqTest.java
- src/test/java/io/vavr/jackson/datatype/set/SetTest.java
> serializable comparators

- src/main/java/io/vavr/jackson/datatype/deserialize/LazyDeserializer.java
- src/main/java/io/vavr/jackson/datatype/deserialize/VavrDeserializers.java
- src/main/java/io/vavr/jackson/datatype/serialize/LazySerializer.java
- src/main/java/io/vavr/jackson/datatype/serialize/VavrSerializers.java
- src/test/java/io/vavr/jackson/datatype/LazyTest.java
> LazySerializer and LazyDeserializer are contextual

- src/main/java/io/vavr/jackson/datatype/deserialize/MapDeserializer.java
- src/main/java/io/vavr/jackson/datatype/deserialize/MaplikeDeserializer.java
- src/main/java/io/vavr/jackson/datatype/deserialize/MultimapDeserializer.java
- src/main/java/io/vavr/jackson/datatype/deserialize/VavrDeserializers.java
- src/test/java/io/vavr/jackson/datatype/map/MapTest.java
- src/test/java/io/vavr/jackson/datatype/multimap/MultimapTest.java
Fix https://github.com/vavr-io/vavr-jackson/issues/131
> Support deserializeNullAsEmpty for maps

- src/main/java/io/vavr/jackson/datatype/deserialize/VavrDeserializers.java
- src/test/java/io/vavr/jackson/issues/Issue165Test.java
Fix https://github.com/vavr-io/vavr-jackson/issues/165
> Deserialize classes Option.{Some,None}

- .travis.yml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12
﻿
> add Jackson version 2.12.0-rc1

- .travis.yml
https://cowtowncoder.medium.com/jackson-2-12-features-eee9456fec75
> Jackson 2.12.0

- src/main/java/io/vavr/jackson/datatype/deserialize/MapDeserializer.java
- src/main/java/io/vavr/jackson/datatype/deserialize/MultimapDeserializer.java
- src/test/java/generator/Generator.java
- src/test/java/generator/JsonCreatorPojo.java
- src/test/java/generator/utils/PoetHelpers.java
- src/test/java/io/vavr/jackson/generated/JsonCreatorPojoTest.java
> fix for #177 

- .travis.yml
- build.gradle
- gradle.properties
This pull request is pretty minimal, but it can enhance getting ride of some vulnerabilities and get benefits and enhancements of the last updates of version 2.14.1 of fasterxml
> Upgrade fasterxml version to 2.14.1

- .github/workflows/main.yml
See https://github.com/vavr-io/vavr-jackson/pull/188
> Add Jackson 2.13.4.2 into the matrix

- gradle.properties
> jackson 2.15.2

- src/main/java/io/vavr/jackson/datatype/deserialize/MapDeserializer.java
- src/test/java/io/vavr/jackson/datatype/map/HashMapJsonMergeTest.java
- src/test/java/io/vavr/jackson/datatype/map/LinkedHashMapJsonMergeTest.java
- src/test/java/io/vavr/jackson/datatype/map/MapJsonMergeTest.java
- src/test/java/io/vavr/jackson/datatype/map/TreeMapJsonMergeTest.java
Follow up to: https://github.com/vavr-io/vavr-jackson/pull/238
> Enable recursive Map merging

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
> Adding devcontainer support

- .github/workflows/build.yml
depends on:
- https://github.com/vavr-io/vavr-jackson/pull/247
> Build on JDK24
